-- MySQL Script generated by MySQL Workbench
-- 02/05/20 15:22:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema todolist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categories` ;

CREATE TABLE IF NOT EXISTS `categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'L\'identifiant de notre catégorie',
  `name` VARCHAR(64) NOT NULL COMMENT 'Le nom de la catégorie',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Le statut de la catégorie (1=active, 2=désactivée)',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'La date de création de la catégorie',
  `updated_at` TIMESTAMP NULL COMMENT 'La date de la dernière mise à jour de la catégorie',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasks` ;

CREATE TABLE IF NOT EXISTS `tasks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'L\'identifiant de notre tâche',
  `title` VARCHAR(128) NOT NULL COMMENT 'Le titre de la tâche',
  `completion` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Le pourcentage de completion de la tâche',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Le statut de la tâche (1=active, 2=archivée)',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'La date de création de la tâche',
  `updated_at` TIMESTAMP NULL COMMENT 'La date de la dernière mise à jour de la tâche',
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_categories_idx` (`category_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `categories`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `categories` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES (1, 'Chemin vers O\'clock', 1, DEFAULT, NULL);
INSERT INTO `categories` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES (2, 'Courses', 1, DEFAULT, NULL);
INSERT INTO `categories` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES (3, 'Formation O\'clock', 1, DEFAULT, NULL);
INSERT INTO `categories` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES (4, 'Titre Professionnel', 1, DEFAULT, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `tasks`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `tasks` (`id`, `title`, `completion`, `status`, `created_at`, `updated_at`, `category_id`) VALUES (1, 'Passer les tests du chemin vers O\'clock', 100, 2, DEFAULT, NULL, 1);
INSERT INTO `tasks` (`id`, `title`, `completion`, `status`, `created_at`, `updated_at`, `category_id`) VALUES (2, 'Contacter Pole Emploi', 100, 2, DEFAULT, NULL, 1);
INSERT INTO `tasks` (`id`, `title`, `completion`, `status`, `created_at`, `updated_at`, `category_id`) VALUES (3, 'Acheter du pain', 0, 1, DEFAULT, NULL, 2);
INSERT INTO `tasks` (`id`, `title`, `completion`, `status`, `created_at`, `updated_at`, `category_id`) VALUES (4, 'Survivre à la première saison', 100, 1, DEFAULT, NULL, 3);
INSERT INTO `tasks` (`id`, `title`, `completion`, `status`, `created_at`, `updated_at`, `category_id`) VALUES (5, 'Maitriser les bases de la programmation informatique', 100, 1, DEFAULT, NULL, 3);
INSERT INTO `tasks` (`id`, `title`, `completion`, `status`, `created_at`, `updated_at`, `category_id`) VALUES (6, 'Rédiger mes dossiers de Titre Professionnel', 0, 1, DEFAULT, NULL, 4);
INSERT INTO `tasks` (`id`, `title`, `completion`, `status`, `created_at`, `updated_at`, `category_id`) VALUES (7, 'Présenter mon projet au jury bienveillant', 0, 1, DEFAULT, NULL, 4);
INSERT INTO `tasks` (`id`, `title`, `completion`, `status`, `created_at`, `updated_at`, `category_id`) VALUES (8, 'Mon premier MCD', 100, 1, DEFAULT, NULL, 3);

COMMIT;

